### ISSUE TITLE
http too many resquests

### ISSUE THREAD

**Issue by matholiveira91** [Jul10l1r4/getrails#5]
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

[proxychains] DLL init: proxychains-ng 4.11
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  www.google.com:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  www.google.com:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  www.google.com:443  ...  OK

**Comment by Jul10l1r4** [comment]
Manda  o erro completo pfv

**Comment by Jul10l1r4** [comment]
Esse erro é pela classificação do ip q vc está usando, imagino q tenha tentado o proxychains configurado na rede onion né?! O google consulta a reputação do ip e responde "too many req."
